server:
  port: 8090

spring:
  datasource:
    username: root
    password: Bucaicai
    url: jdbc:mysql://192.10.10.10:3306/test?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 200
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    web:
      pageable:
        # 分页页码从第一页开始
        one-indexed-parameters: true